### ISSUE TITLE
Switch to testing repo ?

### ISSUE THREAD

**Issue by DraGiuS** [syncreticlinux/manjaro-tools-profile#3]
That's another idea, because there are enough stable and more fresh than the default repo.

**Comment by mkowal07** [comment]
I changed the configuration on the daily builds to testing, we will see how it goes and evaluate.
[https://ci.mkxt.net/iso/syncretic/kde/](https://ci.mkxt.net/iso/syncretic/kde/)

Assuming it builds correctly, next build published should use the testing repos.

**Comment by mkowal07** [comment]
Completed.
